/**
 * Traditional Redux Action Types for Notes & Note-related UI
 */
export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const ARCHIVE_NOTE_SUCCESS = "ARCHIVE_NOTE_SUCCESS";
export const RESTORE_NOTE_SUCCESS = "RESTORE_NOTE_SUCCESS";

export const SET_ACTIVE_NOTE = "SET_ACTIVE_NOTE";
export const CLEAR_ACTIVE_NOTE = "CLEAR_ACTIVE_NOTE";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const SET_NOTE_TO_DELETE = "SET_NOTE_TO_DELETE";
export const CLEAR_NOTE_TO_DELETE = "CLEAR_NOTE_TO_DELETE";
export const SET_IS_DELETING = "SET_IS_DELETING";
